
package org.haijun.study.cxf.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-09T23:17:02.170+08:00
 * Generated source version: 3.2.4
 *
 */
public final class Baeldung_BaeldungImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://impl.cxf.study.haijun.org/", "testCxf1");

    private Baeldung_BaeldungImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = TestCxf1.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        TestCxf1 ss = new TestCxf1(wsdlURL, SERVICE_NAME);
        Baeldung port = ss.getBaeldungImplPort();

        {
        System.out.println("Invoking hello...");
        java.lang.String _hello_parameters = "";
        java.lang.String _hello__return = port.hello(_hello_parameters);
        System.out.println("hello.result=" + _hello__return);


        }
        {
        System.out.println("Invoking getusers...");
        java.util.List<org.haijun.study.cxf.client.User> _getusers__return = port.getusers();
        System.out.println("getusers.result=" + _getusers__return);


        }
        {
        System.out.println("Invoking register...");
        org.haijun.study.cxf.client.Student _register_student = null;
        java.lang.String _register__return = port.register(_register_student);
        System.out.println("register.result=" + _register__return);


        }

        System.exit(0);
    }

}
