package org.haijun.study.cxf.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.4
 * 2018-06-09T23:17:02.204+08:00
 * Generated source version: 3.2.4
 *
 */
@WebServiceClient(name = "testCxf1",
                  wsdlLocation = "http://localhost:8865/webservice/baeldungsever?wsdl",
                  targetNamespace = "http://impl.cxf.study.haijun.org/")
public class TestCxf1 extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://impl.cxf.study.haijun.org/", "testCxf1");
    public final static QName BaeldungImplPort = new QName("http://impl.cxf.study.haijun.org/", "BaeldungImplPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8865/webservice/baeldungsever?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(TestCxf1.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "http://localhost:8865/webservice/baeldungsever?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public TestCxf1(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public TestCxf1(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TestCxf1() {
        super(WSDL_LOCATION, SERVICE);
    }

    public TestCxf1(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public TestCxf1(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public TestCxf1(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns Baeldung
     */
    @WebEndpoint(name = "BaeldungImplPort")
    public Baeldung getBaeldungImplPort() {
        return super.getPort(BaeldungImplPort, Baeldung.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Baeldung
     */
    @WebEndpoint(name = "BaeldungImplPort")
    public Baeldung getBaeldungImplPort(WebServiceFeature... features) {
        return super.getPort(BaeldungImplPort, Baeldung.class, features);
    }

}
